#!/bin/bash
# _
#| |__  ___ _ ____      ___ __ ___    _ __ ___
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \  | '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | | (__
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_| |_|  \___|
#          |_|
#
# Build: Surface Book 2 
# Version: 2.5

. "${HOME}/.cache/wal/colors.sh"

# CURSOR THEME (get rid of default X style)
xsetroot -cursor_name left_ptr

#===[ AUTOSTART ]===#
python /home/r3dux/bin/env/env.py


#===[ WORKSPACES ]===#
#bspc monitor -d 'dev'  'www' 'code' 'chat' 'media' 'sys' 'files' 'vbox' 'github' 'email'
#bspc monitor -d ' dev'  ' www' ' code' ' chat' ' media' ' sys' ' files' ' vbox' ' github' ' email'
#bspc monitor -d '1'  '2' '3' '4' '5' '6' '7' '8' '9' '10'
#bspc monitor -d 'I'  'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X'
#bspc monitor -d ' '  ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '
#bspc monitor -d ' '  ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '

bspc monitor -d ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '



#===[ WINDOW SETTINGS ]===#

bspc config normal_border_color             $background
bspc config active_border_color             $background
bspc config focused_border_color            $color1
bspc config presel_feedback_color           $color3
bspc config center_pseudo_tiled             true
bspc config center_floating                 true
bspc config focus_by_distance               true


#===[ LAYOUT SETTINGS ]===#

bspc config border_width                    2
bspc config window_gap                      0
bspc config top_padding                     60
bspc config bottom_padding                  0
bspc config left_padding                    0
bspc config righ_padding                    0
bspc config split_ratio                     0.525
bspc config auto_alternate                  true
bspc config history_aware_focus             true
bspc config remove_disabled_monitors        true
bspc config merge_overlapping_monitors      true
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

#===[ MOUSE SETTINGS ]===#

bspc config focus_follows_pointer           true
bspc config pointer_follows_focus           false
bspc config pointer_modifier mod4


#===[ SCRATCHPAD ]===#
bspc rule -a st-256color:scratchy state=floating sticky=on rectangle=2000x1500+0+0 center=true border_width=0


#===[ COLORS ]===#
background=$color0
foreground=$color7
foreground_alt=$color7
#primary=$color1
primary=$color2
secondary=$color2
alert=$color3


#===[ WINDOW RULES ]===#
#bspc rule -a st-256color:st-256color rectangle=1800x1250+0+0 center=true
bspc rule -a st-256color:st-256color rectangle=2250x1750+0+0 center=true
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Krita desktop='^5' state=floating follow=on
bspc rule -a qutebrowser rectangle=2250x1750+0+0 center=true
bspc rule -a firefox state=tiled rectangle=2000x1500+0+0 center=true
bspc rule -a "spotify" desktop='^6' state=floating rectangle=2500x1500+0+0 center=true
bspc rule -a mplayer2 state=floating
bspc rule -a Viewnior state=floating center=true
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a st-256color:pulsemixer state=floating rectangle=1000x600+0+0 center=true
bspc rule -a st-256color:iwctl state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a st-256color:ytop state=floating rectangle=2000x1500+0+0 center=true
bspc rule -a st-256color:scratchy state=floating
bspc rule -a Surf state=floating rectangle=2250x1750+0+0 center=true
bspc rule -a Chromium state=floating rectangle=2250x1750+0+0 center=true
bspc rule -a Emacs state=tiled rectangle=2750x1750+0+0 center=true
bspc rule -a kdenlive state=tiled rectangle=2750x1750+0+0 center=true
bspc rule -a Sxiv state=floating rectangle=2500x1500+0+0 center=true
bspc rule -a qpaeq state=floating rectangle=1000x400+0+0 center=true
bspc rule -a Pavucontrol state=floating rectangle=1000x1000+0+0 center=true
bspc rule -a Nitrogen state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a Lxappearance state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a Lightdm-settings state=floating rectangle=1500x1000+0+0 center=true
bspc rule -a "Bluetooth Devices" state=floating rectangle=500x500+0+0 center=true
bspc rule -a pcmanfm desktop='^7' state=floating rectangle=1000x1000+0+0 center=true
bspc rule -a "VirtualBox Manager" desktop='^8' state=floating rectangle=2000x1500+0+0 center=true
bspc rule -a "Kvantum Manager" state=floating rectangle=2000x1500+0+0 center=true
bspc rule -a "pamac-manager" state=floating rectangle=2000x1500+0+0 center=true
bspc rule -a "Network Connections" state=floating rectangle=1500x1000+0+0 center=true
